#ifndef MAIN_PART_LASER_DEFORMATION_POLICY_HLSL
#define MAIN_PART_LASER_DEFORMATION_POLICY_HLSL
struct MainPartLaserDeformation
{
  float3 localPosition;
  float proceduralPhase;
  float2 animationPhase;
  float pickingLane;
};
MainPartLaserDeformation EvaluateMainPartLaserDeformation(
    float3 v0, float2 v1, float3 v2, float3 v3, float3 v4, uint4 v6)
{
  float4 partPositionState = 0, animationTransformState = 0;
  float4 viewProjectionState = 0, normalAndTangentState = 0;
  float4 materialCoordinateState = 0, effectAnimationState = 0;
  float4 materialSampleState = 0, profileMaterialState = 0;
  float4 clusterMaskState = 0, lightIteratorState = 0;
partPositionState.xz = float2(0,1);
  animationTransformState.xz = float2(0,1);
  viewProjectionState.xyz = v3.xyz + -v0.xyz;
  normalAndTangentState.xy = (int2)v6.yz & int2(1023,0xffff);
  partPositionState.w = (uint)normalAndTangentState.y;
  partPositionState.w = 1.52590219e-05 * partPositionState.w;
  viewProjectionState.xyz = viewProjectionState.xyz * partPositionState.www + v0.xyz;
  normalAndTangentState.yz = cb_laser_displacement.fWaveNoiseIntensity * viewProjectionState.xy;
  animationTransformState.w = dot(normalAndTangentState.yz, float2(0.366025418,0.366025418));
  normalAndTangentState.yz = viewProjectionState.xy * cb_laser_displacement.fWaveNoiseIntensity + animationTransformState.ww;
  normalAndTangentState.yz = floor(normalAndTangentState.yz);
  materialCoordinateState.xy = float2(0.00346020772,0.00346020772) * normalAndTangentState.yz;
  materialCoordinateState.xy = floor(materialCoordinateState.xy);
  materialCoordinateState.xy = -materialCoordinateState.xy * float2(289,289) + normalAndTangentState.yz;
  materialCoordinateState.zw = viewProjectionState.xy * cb_laser_displacement.fWaveNoiseIntensity + -normalAndTangentState.yz;
  animationTransformState.w = dot(normalAndTangentState.yz, float2(0.211324871,0.211324871));
  normalAndTangentState.yz = materialCoordinateState.zw + animationTransformState.ww;
  animationTransformState.w = cmp(normalAndTangentState.z < normalAndTangentState.y);
  effectAnimationState.xyzw = animationTransformState.wwww ? float4(1,0,-1,-0) : float4(0,1,-0,-1);
  animationTransformState.y = effectAnimationState.y;
  animationTransformState.xyz = materialCoordinateState.yyy + animationTransformState.xyz;
  materialCoordinateState.yzw = animationTransformState.xyz * animationTransformState.xyz;
  animationTransformState.xyz = materialCoordinateState.yzw * float3(34,34,34) + animationTransformState.xyz;
  materialCoordinateState.yzw = float3(0.00346020772,0.00346020772,0.00346020772) * animationTransformState.xyz;
  materialCoordinateState.yzw = floor(materialCoordinateState.yzw);
  animationTransformState.xyz = -materialCoordinateState.yzw * float3(289,289,289) + animationTransformState.xyz;
  animationTransformState.xyz = animationTransformState.xyz + materialCoordinateState.xxx;
  partPositionState.y = effectAnimationState.x;
  partPositionState.xyz = animationTransformState.xyz + partPositionState.xyz;
  animationTransformState.xyz = partPositionState.xyz * partPositionState.xyz;
  partPositionState.xyz = animationTransformState.xyz * float3(34,34,34) + partPositionState.xyz;
  animationTransformState.xyz = float3(0.00346020772,0.00346020772,0.00346020772) * partPositionState.xyz;
  animationTransformState.xyz = floor(animationTransformState.xyz);
  partPositionState.xyz = -animationTransformState.xyz * float3(289,289,289) + partPositionState.xyz;
  partPositionState.xyz = float3(0.024390243,0.024390243,0.024390243) * partPositionState.xyz;
  partPositionState.xyz = frac(partPositionState.xyz);
  animationTransformState.xyz = partPositionState.xyz * float3(2,2,2) + float3(-0.5,-0.5,-0.5);
  partPositionState.xyz = partPositionState.xyz * float3(2,2,2) + float3(-1,-1,-1);
  animationTransformState.xyz = floor(animationTransformState.xyz);
  animationTransformState.xyz = -animationTransformState.xyz + partPositionState.xyz;
  partPositionState.xyz = float3(-0.5,-0.5,-0.5) + abs(partPositionState.xyz);
  materialCoordinateState.xyz = partPositionState.xyz * partPositionState.xyz;
  materialCoordinateState.xyz = animationTransformState.xyz * animationTransformState.xyz + materialCoordinateState.xyz;
  materialCoordinateState.xyz = -materialCoordinateState.xyz * float3(0.853734732,0.853734732,0.853734732) + float3(1.79284286,1.79284286,1.79284286);
  materialSampleState.x = dot(normalAndTangentState.yz, normalAndTangentState.yz);
  profileMaterialState.xyzw = float4(0.211324871,0.211324871,-0.577350259,-0.577350259) + normalAndTangentState.yzyz;
  profileMaterialState.xy = profileMaterialState.xy + effectAnimationState.zw;
  materialSampleState.y = dot(profileMaterialState.xy, profileMaterialState.xy);
  materialSampleState.z = dot(profileMaterialState.zw, profileMaterialState.zw);
  effectAnimationState.xyz = float3(0.5,0.5,0.5) + -materialSampleState.xyz;
  effectAnimationState.xyz = max(float3(0,0,0), effectAnimationState.xyz);
  effectAnimationState.xyz = effectAnimationState.xyz * effectAnimationState.xyz;
  effectAnimationState.xyz = effectAnimationState.xyz * effectAnimationState.xyz;
  materialCoordinateState.xyz = effectAnimationState.xyz * materialCoordinateState.xyz;
  partPositionState.x = partPositionState.x * normalAndTangentState.z;
  partPositionState.yz = profileMaterialState.yw * partPositionState.yz;
  effectAnimationState.yz = animationTransformState.yz * profileMaterialState.xz + partPositionState.yz;
  effectAnimationState.x = animationTransformState.x * normalAndTangentState.y + partPositionState.x;
  partPositionState.x = dot(materialCoordinateState.xyz, effectAnimationState.xyz);
  partPositionState.x = 130 * partPositionState.x;
  partPositionState.y = cb_fTime * cb_laser_displacement.fDisplacementSpeed + viewProjectionState.y;
  partPositionState.y = sin(partPositionState.y);
  partPositionState.x = partPositionState.y * partPositionState.x;
  partPositionState.x = cb_laser_displacement.fDisplacementStrength * partPositionState.x;
  partPositionState.y = cb_fTime * -cb_laser_displacement.fDisplacementSpeed;
  partPositionState.z = viewProjectionState.y * cb_laser_displacement.fSliceSize + partPositionState.y;
  partPositionState.z = sin(partPositionState.z);
  partPositionState.z = cmp(partPositionState.z >= 0.5);
  partPositionState.z = partPositionState.z ? 1.000000 : 0;
  partPositionState.x = partPositionState.z * partPositionState.x;
  animationTransformState.xyz = v4.xyz * float3(2,2,2) + float3(-1,-1,-1);
  normalAndTangentState.yzw = v2.xyz * float3(2,2,2) + float3(-1,-1,-1);
  animationTransformState.xyz = -normalAndTangentState.yzw + animationTransformState.xyz;
  animationTransformState.xyz = animationTransformState.xyz * partPositionState.www + normalAndTangentState.yzw;
  partPositionState.xzw = animationTransformState.xyz * partPositionState.xxx;
  materialCoordinateState.xz = float2(0,1);
  normalAndTangentState.yz = cb_fTime * cb_laser_displacement.fGlitchSpeed + viewProjectionState.xz;
  animationTransformState.w = dot(normalAndTangentState.yz, float2(0.366025418,0.366025418));
  effectAnimationState.xy = normalAndTangentState.yz + animationTransformState.ww;
  effectAnimationState.xy = floor(effectAnimationState.xy);
  effectAnimationState.zw = float2(0.00346020772,0.00346020772) * effectAnimationState.xy;
  effectAnimationState.zw = floor(effectAnimationState.zw);
  effectAnimationState.zw = -effectAnimationState.zw * float2(289,289) + effectAnimationState.xy;
  normalAndTangentState.yz = -effectAnimationState.xy + normalAndTangentState.yz;
  animationTransformState.w = dot(effectAnimationState.xy, float2(0.211324871,0.211324871));
  normalAndTangentState.yz = normalAndTangentState.yz + animationTransformState.ww;
  animationTransformState.w = cmp(normalAndTangentState.z < normalAndTangentState.y);
  materialSampleState.xyzw = animationTransformState.wwww ? float4(1,0,-1,-0) : float4(0,1,-0,-1);
  materialCoordinateState.y = materialSampleState.y;
  materialCoordinateState.xyz = effectAnimationState.www + materialCoordinateState.xyz;
  effectAnimationState.xyw = materialCoordinateState.xyz * materialCoordinateState.xyz;
  materialCoordinateState.xyz = effectAnimationState.xyw * float3(34,34,34) + materialCoordinateState.xyz;
  effectAnimationState.xyw = float3(0.00346020772,0.00346020772,0.00346020772) * materialCoordinateState.xyz;
  effectAnimationState.xyw = floor(effectAnimationState.xyw);
  materialCoordinateState.xyz = -effectAnimationState.xyw * float3(289,289,289) + materialCoordinateState.xyz;
  materialCoordinateState.xyz = materialCoordinateState.xyz + effectAnimationState.zzz;
  effectAnimationState.xz = float2(0,1);
  effectAnimationState.y = materialSampleState.x;
  materialCoordinateState.xyz = effectAnimationState.xyz + materialCoordinateState.xyz;
  effectAnimationState.xyz = materialCoordinateState.xyz * materialCoordinateState.xyz;
  materialCoordinateState.xyz = effectAnimationState.xyz * float3(34,34,34) + materialCoordinateState.xyz;
  effectAnimationState.xyz = float3(0.00346020772,0.00346020772,0.00346020772) * materialCoordinateState.xyz;
  effectAnimationState.xyz = floor(effectAnimationState.xyz);
  materialCoordinateState.xyz = -effectAnimationState.xyz * float3(289,289,289) + materialCoordinateState.xyz;
  materialCoordinateState.xyz = float3(0.024390243,0.024390243,0.024390243) * materialCoordinateState.xyz;
  materialCoordinateState.xyz = frac(materialCoordinateState.xyz);
  effectAnimationState.xyz = materialCoordinateState.xyz * float3(2,2,2) + float3(-0.5,-0.5,-0.5);
  materialCoordinateState.xyz = materialCoordinateState.xyz * float3(2,2,2) + float3(-1,-1,-1);
  effectAnimationState.xyz = floor(effectAnimationState.xyz);
  effectAnimationState.xyz = -effectAnimationState.xyz + materialCoordinateState.xyz;
  materialCoordinateState.xyz = float3(-0.5,-0.5,-0.5) + abs(materialCoordinateState.xyz);
  profileMaterialState.xyz = materialCoordinateState.xyz * materialCoordinateState.xyz;
  profileMaterialState.xyz = effectAnimationState.xyz * effectAnimationState.xyz + profileMaterialState.xyz;
  profileMaterialState.xyz = -profileMaterialState.xyz * float3(0.853734732,0.853734732,0.853734732) + float3(1.79284286,1.79284286,1.79284286);
  clusterMaskState.x = dot(normalAndTangentState.yz, normalAndTangentState.yz);
  lightIteratorState.xyzw = float4(0.211324871,0.211324871,-0.577350259,-0.577350259) + normalAndTangentState.yzyz;
  lightIteratorState.xy = lightIteratorState.xy + materialSampleState.zw;
  clusterMaskState.y = dot(lightIteratorState.xy, lightIteratorState.xy);
  clusterMaskState.z = dot(lightIteratorState.zw, lightIteratorState.zw);
  materialSampleState.xyz = float3(0.5,0.5,0.5) + -clusterMaskState.xyz;
  materialSampleState.xyz = max(float3(0,0,0), materialSampleState.xyz);
  materialSampleState.xyz = materialSampleState.xyz * materialSampleState.xyz;
  materialSampleState.xyz = materialSampleState.xyz * materialSampleState.xyz;
  materialSampleState.xyz = materialSampleState.xyz * profileMaterialState.xyz;
  animationTransformState.w = materialCoordinateState.x * normalAndTangentState.z;
  normalAndTangentState.zw = lightIteratorState.yw * materialCoordinateState.yz;
  materialCoordinateState.yz = effectAnimationState.yz * lightIteratorState.xz + normalAndTangentState.zw;
  materialCoordinateState.x = effectAnimationState.x * normalAndTangentState.y + animationTransformState.w;
  animationTransformState.w = dot(materialSampleState.xyz, materialCoordinateState.xyz);
  animationTransformState.w = 130 * animationTransformState.w;
  animationTransformState.w = sin(animationTransformState.w);
  animationTransformState.w = cmp(animationTransformState.w >= 0.800000012);
  animationTransformState.w = animationTransformState.w ? 1.000000 : 0;
  animationTransformState.w = cb_laser_displacement.fDisplacementStrength * animationTransformState.w;
  partPositionState.xzw = animationTransformState.www * animationTransformState.xyz + partPositionState.xzw;
  animationTransformState.x = cb_fTime * cb_laser_displacement.fDisplacementSpeed;
  animationTransformState.y = viewProjectionState.y * cb_laser_displacement.fSliceSize + animationTransformState.x;
  animationTransformState.y = sin(animationTransformState.y);
  animationTransformState.y = cmp(animationTransformState.y >= 0.5);
  animationTransformState.y = animationTransformState.y ? 1.000000 : 0;
  animationTransformState.y = cb_laser_displacement.fDisplacementStrength * animationTransformState.y;
  partPositionState.xzw = animationTransformState.yyy * cb_laser_displacement.vSliceDirection.xyz + partPositionState.xzw;
  animationTransformState.y = -cb_laser_displacement.fFlickerFrequencyValue + -cb_laser_displacement.fFlickerFrequencyOffset;
  animationTransformState.y = cb_fTime * animationTransformState.y;
  animationTransformState.y = sin(animationTransformState.y);
  animationTransformState.y = cmp(animationTransformState.y >= 0.899999976);
  animationTransformState.z = cb_fTime * -cb_laser_displacement.fFlickerFrequencyValue;
  animationTransformState.z = sin(animationTransformState.z);
  animationTransformState.z = cmp(animationTransformState.z >= 0.5);
  animationTransformState.yz = animationTransformState.yz ? float2(1,1) : 0;
  animationTransformState.y = animationTransformState.z * animationTransformState.y;
  partPositionState.xzw = animationTransformState.yyy * partPositionState.xzw;
  animationTransformState.z = -cb_laser_displacement.fDisplacementFadeValue + v1.y;
  animationTransformState.z = cb_laser_displacement.fDisplacementFadeRange + animationTransformState.z;
  animationTransformState.z = saturate(animationTransformState.z / cb_laser_displacement.fDisplacementFadeRange);
  animationTransformState.z = 1 + -animationTransformState.z;
  partPositionState.xzw = partPositionState.xzw * animationTransformState.zzz + viewProjectionState.xyz;

  MainPartLaserDeformation result;
  result.localPosition = partPositionState.xzw;
  result.proceduralPhase = partPositionState.y;
  result.animationPhase = animationTransformState.xy;
  result.pickingLane = normalAndTangentState.x;
  return result;
}
#endif
