#ifndef MAIN_PART_LASER_DISPLACEMENT_COLOR_POLICY_HLSL
#define MAIN_PART_LASER_DISPLACEMENT_COLOR_POLICY_HLSL
float3 EvaluateMainPartLaserDisplacementColor(
    float3 localPosition, float proceduralPhase, float2 animationPhase)
{
  float4 partPositionState = float4(
      localPosition.x, proceduralPhase, localPosition.y, localPosition.z);
  float4 animationTransformState = float4(animationPhase, 0, 0);
  float4 viewProjectionState = 0, normalAndTangentState = 0;
  float4 materialCoordinateState = 0, effectAnimationState = 0;
  float4 materialSampleState = 0, profileMaterialState = 0;
animationTransformState.zw = cb_laser_displacement.fWaveNoiseIntensity * partPositionState.xz;
  animationTransformState.z = dot(animationTransformState.zw, float2(0.366025418,0.366025418));
  animationTransformState.zw = partPositionState.xz * cb_laser_displacement.fWaveNoiseIntensity + animationTransformState.zz;
  animationTransformState.zw = floor(animationTransformState.zw);
  viewProjectionState.xy = partPositionState.xz * cb_laser_displacement.fWaveNoiseIntensity + -animationTransformState.zw;
  viewProjectionState.z = dot(animationTransformState.zw, float2(0.211324871,0.211324871));
  viewProjectionState.xy = viewProjectionState.xy + viewProjectionState.zz;
  viewProjectionState.zw = float2(0.00346020772,0.00346020772) * animationTransformState.zw;
  viewProjectionState.zw = floor(viewProjectionState.zw);
  animationTransformState.zw = -viewProjectionState.zw * float2(289,289) + animationTransformState.zw;
  viewProjectionState.z = cmp(viewProjectionState.y < viewProjectionState.x);
  materialCoordinateState.xyzw = viewProjectionState.zzzz ? float4(1,0,-1,-0) : float4(0,1,-0,-1);
  effectAnimationState.y = materialCoordinateState.y;
  effectAnimationState.xz = float2(0,1);
  normalAndTangentState.yzw = effectAnimationState.xyz + animationTransformState.www;
  effectAnimationState.xyz = normalAndTangentState.yzw * normalAndTangentState.yzw;
  normalAndTangentState.yzw = effectAnimationState.xyz * float3(34,34,34) + normalAndTangentState.yzw;
  effectAnimationState.xyz = float3(0.00346020772,0.00346020772,0.00346020772) * normalAndTangentState.yzw;
  effectAnimationState.xyz = floor(effectAnimationState.xyz);
  normalAndTangentState.yzw = -effectAnimationState.xyz * float3(289,289,289) + normalAndTangentState.yzw;
  normalAndTangentState.yzw = normalAndTangentState.yzw + animationTransformState.zzz;
  effectAnimationState.y = materialCoordinateState.x;
  effectAnimationState.xz = float2(0,1);
  normalAndTangentState.yzw = effectAnimationState.xyz + normalAndTangentState.yzw;
  effectAnimationState.xyz = normalAndTangentState.yzw * normalAndTangentState.yzw;
  normalAndTangentState.yzw = effectAnimationState.xyz * float3(34,34,34) + normalAndTangentState.yzw;
  effectAnimationState.xyz = float3(0.00346020772,0.00346020772,0.00346020772) * normalAndTangentState.yzw;
  effectAnimationState.xyz = floor(effectAnimationState.xyz);
  normalAndTangentState.yzw = -effectAnimationState.xyz * float3(289,289,289) + normalAndTangentState.yzw;
  normalAndTangentState.yzw = float3(0.024390243,0.024390243,0.024390243) * normalAndTangentState.yzw;
  normalAndTangentState.yzw = frac(normalAndTangentState.yzw);
  effectAnimationState.xyz = normalAndTangentState.yzw * float3(2,2,2) + float3(-0.5,-0.5,-0.5);
  normalAndTangentState.yzw = normalAndTangentState.yzw * float3(2,2,2) + float3(-1,-1,-1);
  effectAnimationState.xyz = floor(effectAnimationState.xyz);
  effectAnimationState.xyz = -effectAnimationState.xyz + normalAndTangentState.yzw;
  normalAndTangentState.yzw = float3(-0.5,-0.5,-0.5) + abs(normalAndTangentState.yzw);
  animationTransformState.z = normalAndTangentState.y * viewProjectionState.y;
  materialSampleState.x = effectAnimationState.x * viewProjectionState.x + animationTransformState.z;
  profileMaterialState.x = dot(viewProjectionState.xy, viewProjectionState.xy);
  viewProjectionState.xyzw = float4(0.211324871,0.211324871,-0.577350259,-0.577350259) + viewProjectionState.xyxy;
  profileMaterialState.z = dot(viewProjectionState.zw, viewProjectionState.zw);
  viewProjectionState.xy = viewProjectionState.xy + materialCoordinateState.zw;
  profileMaterialState.y = dot(viewProjectionState.xy, viewProjectionState.xy);
  materialCoordinateState.xyz = float3(0.5,0.5,0.5) + -profileMaterialState.xyz;
  materialCoordinateState.xyz = max(float3(0,0,0), materialCoordinateState.xyz);
  materialCoordinateState.xyz = materialCoordinateState.xyz * materialCoordinateState.xyz;
  materialCoordinateState.xyz = materialCoordinateState.xyz * materialCoordinateState.xyz;
  profileMaterialState.xyz = normalAndTangentState.yzw * normalAndTangentState.yzw;
  animationTransformState.zw = normalAndTangentState.zw * viewProjectionState.yw;
  materialSampleState.yz = effectAnimationState.yz * viewProjectionState.xz + animationTransformState.zw;
  viewProjectionState.xyz = effectAnimationState.xyz * effectAnimationState.xyz + profileMaterialState.xyz;
  viewProjectionState.xyz = -viewProjectionState.xyz * float3(0.853734732,0.853734732,0.853734732) + float3(1.79284286,1.79284286,1.79284286);
  viewProjectionState.xyz = materialCoordinateState.xyz * viewProjectionState.xyz;
  animationTransformState.z = dot(viewProjectionState.xyz, materialSampleState.xyz);
  animationTransformState.z = 130 * animationTransformState.z;
  animationTransformState.w = cb_fTime * cb_laser_displacement.fDisplacementSpeed + partPositionState.z;
  animationTransformState.w = sin(animationTransformState.w);
  animationTransformState.z = animationTransformState.w * animationTransformState.z;
  animationTransformState.z = cb_laser_displacement.fDisplacementStrength * animationTransformState.z;
  partPositionState.y = partPositionState.z * cb_laser_displacement.fSliceSize + partPositionState.y;
  partPositionState.y = sin(partPositionState.y);
  partPositionState.y = cmp(partPositionState.y >= 0.5);
  partPositionState.y = partPositionState.y ? 1.000000 : 0;
  partPositionState.y = partPositionState.y * animationTransformState.z;
  partPositionState.xw = cb_fTime * cb_laser_displacement.fGlitchSpeed + partPositionState.xw;
  partPositionState.z = partPositionState.z * cb_laser_displacement.fSliceSize + animationTransformState.x;
  partPositionState.z = sin(partPositionState.z);
  partPositionState.z = cmp(partPositionState.z >= 0.5);
  animationTransformState.x = dot(partPositionState.xw, float2(0.366025418,0.366025418));
  animationTransformState.xz = animationTransformState.xx + partPositionState.xw;
  animationTransformState.xz = floor(animationTransformState.xz);
  partPositionState.xw = -animationTransformState.xz + partPositionState.xw;
  animationTransformState.w = dot(animationTransformState.xz, float2(0.211324871,0.211324871));
  partPositionState.xw = animationTransformState.ww + partPositionState.xw;
  viewProjectionState.xy = float2(0.00346020772,0.00346020772) * animationTransformState.xz;
  viewProjectionState.xy = floor(viewProjectionState.xy);
  animationTransformState.xz = -viewProjectionState.xy * float2(289,289) + animationTransformState.xz;
  animationTransformState.w = cmp(partPositionState.w < partPositionState.x);
  viewProjectionState.xyzw = animationTransformState.wwww ? float4(1,0,-1,-0) : float4(0,1,-0,-1);
  materialCoordinateState.y = viewProjectionState.y;
  materialCoordinateState.xz = float2(0,1);
  normalAndTangentState.yzw = materialCoordinateState.xyz + animationTransformState.zzz;
  materialCoordinateState.xyz = normalAndTangentState.yzw * normalAndTangentState.yzw;
  normalAndTangentState.yzw = materialCoordinateState.xyz * float3(34,34,34) + normalAndTangentState.yzw;
  materialCoordinateState.xyz = float3(0.00346020772,0.00346020772,0.00346020772) * normalAndTangentState.yzw;
  materialCoordinateState.xyz = floor(materialCoordinateState.xyz);
  normalAndTangentState.yzw = -materialCoordinateState.xyz * float3(289,289,289) + normalAndTangentState.yzw;
  animationTransformState.xzw = normalAndTangentState.yzw + animationTransformState.xxx;
  materialCoordinateState.y = viewProjectionState.x;
  materialCoordinateState.xz = float2(0,1);
  animationTransformState.xzw = materialCoordinateState.xyz + animationTransformState.xzw;
  normalAndTangentState.yzw = animationTransformState.xzw * animationTransformState.xzw;
  animationTransformState.xzw = normalAndTangentState.yzw * float3(34,34,34) + animationTransformState.xzw;
  normalAndTangentState.yzw = float3(0.00346020772,0.00346020772,0.00346020772) * animationTransformState.xzw;
  normalAndTangentState.yzw = floor(normalAndTangentState.yzw);
  animationTransformState.xzw = -normalAndTangentState.yzw * float3(289,289,289) + animationTransformState.xzw;
  animationTransformState.xzw = float3(0.024390243,0.024390243,0.024390243) * animationTransformState.xzw;
  animationTransformState.xzw = frac(animationTransformState.xzw);
  normalAndTangentState.yzw = animationTransformState.xzw * float3(2,2,2) + float3(-0.5,-0.5,-0.5);
  animationTransformState.xzw = animationTransformState.xzw * float3(2,2,2) + float3(-1,-1,-1);
  normalAndTangentState.yzw = floor(normalAndTangentState.yzw);
  normalAndTangentState.yzw = -normalAndTangentState.yzw + animationTransformState.xzw;
  animationTransformState.xzw = float3(-0.5,-0.5,-0.5) + abs(animationTransformState.xzw);
  viewProjectionState.x = animationTransformState.x * partPositionState.w;
  materialCoordinateState.x = normalAndTangentState.y * partPositionState.x + viewProjectionState.x;
  effectAnimationState.x = dot(partPositionState.xw, partPositionState.xw);
  materialSampleState.xyzw = float4(0.211324871,0.211324871,-0.577350259,-0.577350259) + partPositionState.xwxw;
  effectAnimationState.z = dot(materialSampleState.zw, materialSampleState.zw);
  materialSampleState.xy = materialSampleState.xy + viewProjectionState.zw;
  effectAnimationState.y = dot(materialSampleState.xy, materialSampleState.xy);
  viewProjectionState.xyz = float3(0.5,0.5,0.5) + -effectAnimationState.xyz;
  viewProjectionState.xyz = max(float3(0,0,0), viewProjectionState.xyz);
  viewProjectionState.xyz = viewProjectionState.xyz * viewProjectionState.xyz;
  viewProjectionState.xyz = viewProjectionState.xyz * viewProjectionState.xyz;
  effectAnimationState.xyz = animationTransformState.xzw * animationTransformState.xzw;
  partPositionState.xw = materialSampleState.yw * animationTransformState.zw;
  materialCoordinateState.yz = normalAndTangentState.zw * materialSampleState.xz + partPositionState.xw;
  animationTransformState.xzw = normalAndTangentState.yzw * normalAndTangentState.yzw + effectAnimationState.xyz;
  animationTransformState.xzw = -animationTransformState.xzw * float3(0.853734732,0.853734732,0.853734732) + float3(1.79284286,1.79284286,1.79284286);
  animationTransformState.xzw = viewProjectionState.xyz * animationTransformState.xzw;
  partPositionState.x = dot(animationTransformState.xzw, materialCoordinateState.xyz);
  partPositionState.x = 130 * partPositionState.x;
  partPositionState.x = sin(partPositionState.x);
  partPositionState.x = cmp(partPositionState.x >= 0.800000012);
  partPositionState.xz = partPositionState.xz ? float2(1,1) : 0;
  partPositionState.x = partPositionState.x * cb_laser_displacement.fDisplacementStrength + partPositionState.y;
  partPositionState.x = partPositionState.z * cb_laser_displacement.fDisplacementStrength + partPositionState.x;
  partPositionState.x = partPositionState.x * animationTransformState.y;
  partPositionState.xyz = cb_laser_displacement.vDisplacementColor.xyz * partPositionState.xxx;
  partPositionState.xyz = cb_laser_displacement.vDisplacementColor.www * partPositionState.xyz;
  partPositionState.w = max(0.00999999978, cb_laser_displacement.fDisplacementStrength);
  partPositionState.xyz = partPositionState.xyz / partPositionState.www;

  return partPositionState.xyz;
}
#endif

