// Synthesized semantic family evaluator: transparent_surface_water_tangent_map_dissolve_uv0_fog_cutoff
// Policy assets define typed residual helpers before including this file.

void EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoff(
  float4 smin_sv_position0, float3 smin_view_position0, float2 smin_uv0, float3 smin_normal0, float3 smin_tangent0, float3 smin_bitangent0, float4 smin_vertexcolor0, float3 smin_screen_uv0, float4 smin_fog_color0, float smin_cutoff0, uint smin_sv_isfrontface0, out float4 smout_sv_target0, out float4 smout_sv_target1)
{
  smout_sv_target0 = (float4)0;
  smout_sv_target1 = (float4)0;
  float4 smLocalFloat40 = (float4)0;
  float4 smLocalFloat41 = (float4)0;
  float4 smLocalFloat42 = (float4)0;
  float4 smLocalFloat43 = (float4)0;
  float4 smLocalFloat44 = (float4)0;
  float4 smLocalFloat45 = (float4)0;
  float4 smLocalFloat46 = (float4)0;
  float4 smLocalFloat47 = (float4)0;
  float4 smLocalFloat48 = (float4)0;
  float4 smLocalFloat49 = (float4)0;
  float4 smLocalFloat410 = (float4)0;
  float4 smLocalFloat411 = (float4)0;
  float4 smLocalFloat412 = (float4)0;
  uint4 smLocalUint40 = (uint4)0;
  uint4 smLocalUint41 = (uint4)0;
  float4 smLocalFloat413 = (float4)0;
  float4 smLocalFloat414 = (float4)0;
  float4 smLocalFloat415 = (float4)0;
  float4 smLocalFloat416 = (float4)0;
  float4 smLocalFloat417 = (float4)0;
  float4 smLocalFloat418 = (float4)0;
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy0();
  smLocalFloat40.xyz = tAsg.SampleBias (LinearWrapWrap_s, smin_uv0.xy, cb_fMipBias).ywx;
  smLocalFloat40.z = cmp (smLocalFloat40.z < 0.5);
  if (smLocalFloat40.z != 0) discard;
  smLocalFloat40.zw = cb_dissolve.vScrollSpeed.xy * cb_fTime;
  smLocalFloat40.zw = smin_uv0.xy * cb_dissolve.fScale + smLocalFloat40.zw;
  smLocalFloat41.xyzw = tCutoff.Gather (LinearWrapWrap_s, smLocalFloat40.zw).xyzw;
  smLocalFloat40.zw = max (smLocalFloat41.xz, smLocalFloat41.yw);
  smLocalFloat40.z = max (smLocalFloat40.z, smLocalFloat40.w);
  smLocalFloat40.z = - 0.125 + smLocalFloat40.z;
  smLocalFloat42.xyzw = cmp (smLocalFloat40.zzzz < smLocalFloat41.xyzw);
  smLocalFloat42.xyzw = smLocalFloat42.xyzw ? float4 (1, 1, 1, 1) : 0;
  smLocalFloat40.z = dot (smLocalFloat42.xyzw, float4 (1, 1, 1, 1));
  smLocalFloat40.w = cmp (0 != smLocalFloat40.z);
  smLocalFloat41.xyzw = smLocalFloat42.xyzw * smLocalFloat41.xyzw;
  smLocalFloat41.x = dot (smLocalFloat41.xyzw, float4 (1, 1, 1, 1));
  smLocalFloat40.z = smLocalFloat41.x / smLocalFloat40.z;
  smLocalFloat40.z = smLocalFloat40.w ? smLocalFloat40.z : 0;
  smLocalFloat40.w = cb_fTime * cb_dissolve.fLoopSpeed + smin_cutoff0.x;
  smLocalFloat40.w = frac (smLocalFloat40.w);
  smLocalFloat40.w = smLocalFloat40.w * cb_dissolve.fLoopLength + - cb_dissolve.fLoopOffset;
  smLocalFloat40.z = smLocalFloat40.w + - smLocalFloat40.z;
  smLocalFloat40.w = cmp (abs (smLocalFloat40.z) >= cb_dissolve.fLength);
  if (smLocalFloat40.w != 0) discard;
  smLocalFloat40.z = cb_dissolve.fLength + - abs (smLocalFloat40.z);
  smLocalFloat40.z = saturate (cb_dissolve.fRcpFade * smLocalFloat40.z);
  smLocalFloat40.z = log2 (smLocalFloat40.z);
  smLocalFloat40.z = cb_dissolve.fFadePower * smLocalFloat40.z;
  smLocalFloat40.z = exp2 (smLocalFloat40.z);
  smLocalFloat41.xy = tNor.SampleBias (LinearWrapWrap_s, smin_uv0.xy, cb_fMipBias).xy;
  smLocalFloat41.xy = smLocalFloat41.xy * float2 (1.99215686, 1.99215686) + float2 (- 1, - 1);
  smLocalFloat40.w = dot (smLocalFloat41.xy, smLocalFloat41.xy);
  smLocalFloat40.w = 1 + - smLocalFloat40.w;
  smLocalFloat40.w = max (0, smLocalFloat40.w);
  smLocalFloat40.w = sqrt (smLocalFloat40.w);
  smLocalFloat41.yzw = smin_bitangent0.xyz * smLocalFloat41.yyy;
  smLocalFloat41.xyz = smin_tangent0.xyz * smLocalFloat41.xxx + smLocalFloat41.yzw;
  smLocalFloat41.xyz = smin_normal0.xyz * smLocalFloat40.www + smLocalFloat41.xyz;
  smLocalFloat40.w = dot (smLocalFloat41.xyz, smLocalFloat41.xyz);
  smLocalFloat40.w = rsqrt (smLocalFloat40.w);
  smLocalFloat41.xyz = smLocalFloat41.xyz * smLocalFloat40.www;
  smLocalFloat41.xyz = smin_sv_isfrontface0.xxx ? smLocalFloat41.xyz : - smLocalFloat41.xyz;
  smLocalFloat40.w = dot (smLocalFloat41.xyz, smLocalFloat41.xyz);
  smLocalFloat40.w = rsqrt (smLocalFloat40.w);
  smLocalFloat41.xyz = smLocalFloat41.xyz * smLocalFloat40.www;
  smLocalFloat42.xyzw = tDif.SampleBias (LinearWrapWrap_s, smin_uv0.xy, cb_fMipBias).xyzw;
  smLocalFloat42.xyz = - smin_vertexcolor0.xyz + smLocalFloat42.xyz;
  smLocalFloat42.xyz = smLocalFloat42.www * smLocalFloat42.xyz + smin_vertexcolor0.xyz;
  smLocalFloat43.xyz = cb_dissolve.vEndColor.xyz + - cb_dissolve.vStartColor.xyz;
  smLocalFloat43.xyz = smLocalFloat40.zzz * smLocalFloat43.xyz + cb_dissolve.vStartColor.xyz;
  smLocalFloat42.xyz = - smLocalFloat43.xyz + smLocalFloat42.xyz;
  smLocalFloat42.xyz = smLocalFloat40.zzz * smLocalFloat42.xyz + smLocalFloat43.xyz;
  smLocalFloat40.z = dot (- smin_view_position0.xyz, - smin_view_position0.xyz);
  smLocalFloat40.z = rsqrt (smLocalFloat40.z);
  smLocalFloat43.xyz = - smin_view_position0.xyz * smLocalFloat40.zzz;
  smLocalFloat40.z = dot (- cb_vDirectionalLightDirectionView.xyz, - cb_vDirectionalLightDirectionView.xyz);
  smLocalFloat40.z = rsqrt (smLocalFloat40.z);
  smLocalFloat44.xy = float2 (1, 1) + - smLocalFloat40.xy;
  smLocalFloat40.w = - smLocalFloat44.x * smLocalFloat44.x + 1;
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy1(smLocalFloat40, smLocalFloat43, smLocalFloat44, smLocalFloat45);
  smLocalFloat40.z = rsqrt (smLocalFloat40.z);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy2(smLocalFloat40, smLocalFloat41, smLocalFloat44, smLocalFloat45);
  smLocalFloat40.z = smLocalFloat40.z * 0.5 + 0.5;
  smLocalFloat41.w = dot (smLocalFloat41.xyz, smLocalFloat43.xyz);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy3(smLocalFloat41, smLocalFloat42);
  smLocalFloat40.x = 4 * smLocalFloat40.x;
  smLocalFloat40.x = max (0.100000001, smLocalFloat40.x);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy4(smLocalFloat40, smLocalFloat41, smLocalFloat42);
  smLocalFloat40.x = exp2 (smLocalFloat40.x);
  smLocalFloat40.x = min (1, smLocalFloat40.x);
  smLocalFloat40.x = 1 + - smLocalFloat40.x;
  smLocalFloat40.x = max (0.25, smLocalFloat40.x);
  smLocalFloat40.x = min (0.800000012, smLocalFloat40.x);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy5(smLocalFloat40, smLocalFloat41, smLocalFloat42, smLocalFloat43);
  smLocalFloat40.z = smLocalFloat40.z * smLocalFloat40.z;
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy6(smLocalFloat40, smLocalFloat41, smLocalFloat42);
  smLocalFloat40.z = saturate (smLocalFloat40.z * smLocalFloat40.w);
  smLocalFloat40.x = smLocalFloat40.x * smLocalFloat40.y + smLocalFloat40.z;
  smLocalFloat40.x = saturate (smLocalFloat44.y * 0.25 + smLocalFloat40.x);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy7(smLocalFloat40, smLocalFloat41, smLocalFloat42, smLocalFloat43, smLocalFloat44, smLocalFloat45);
  smLocalFloat40.w = cmp (- smin_view_position0.z < cb_cluster.fClusterMaxFarTotal);
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffClusteredLightingAndSpotCookieAndFrameComposition0(smin_view_position0, smin_screen_uv0, smin_fog_color0, smout_sv_target0, smLocalFloat40, smLocalFloat41, smLocalFloat42, smLocalFloat43, smLocalFloat44, smLocalFloat45, smLocalFloat46, smLocalFloat47, smLocalFloat48, smLocalFloat49, smLocalFloat410, smLocalFloat411, smLocalFloat412, smLocalFloat413, smLocalFloat414, smLocalFloat415, smLocalFloat416, smLocalFloat417);
  smout_sv_target0.w = 1;
  smout_sv_target1.xyzw = float4 (0, 0, 0, 1);
  return;
  EvaluateTransparentSurfaceWaterTangentMapDissolveUv0FogCutoffPolicy8();
}
